### ISSUE TITLE
Adding option to increase stash pages number

### ISSUE THREAD

**Issue by perkel666** [pagewin/MHXXSaveEditor#23]
IDK if this is correct way of doing this...
Since MHXX editor already handles a lot of save files stuff.

Is there a possibility that stash size number can be increased ? I mean there is so much gear to collect in MHXX and you run out of space easily.
Something like 90 pages would be awesome.

Game already has build in dynamic page number since you can upgrade it in game so i think it is possible and could be amazing addition to your project.

I mean in constants there is this stuff:

        public const int SIZEOF_ITEMBOX = 5463;
        public const int TOTAL_ITEM_SLOTS = 2300;

        public const int SIZEOF_EQUIPBOX = 72000;
        public const int TOTAL_EQUIP_SLOTS = 2000;
        public const int SIZEOF_EQUIPMENT = 36;
        public const int SIZEOF_PALICOEQUIPBOX = 36000;
        public const int TOTAL_PALICO_EQUIP = 1000;

**Comment by pagewin** [comment]
Pretty sure that's not possible with the vanilla game. Check out the [wiki page on the format of the save data](https://github.com/pagewin/MHXXSaveEditor/wiki/system-Hunter), adapted from [svanheulen's wiki](https://github.com/svanheulen/mhff/wiki) and [ukee's previous fork of this project](https://github.com/mineminemine/MHXXSaveEditor/wiki/MHXX-'system'-file-structure).

Hunter equipment slots are directly followed by Palico equipment slots within the save file, so those definitely can't be expanded as a contiguous section of the save file. Item slots are followed by some undetermined data. It would be possible to write data into those parts of the save file, but I assume that the 3DS wouldn't recognize it as part of your item boxes, and it's possible that would corrupt your save file based on whatever Capcom shoved there. I think this would require hacking the game to recognize either a larger save file, or a modified save file format.

The constants just help the editor read in that many slots, starting from where the game expects item/equipment data to begin in the save file.

**Comment by perkel666** [comment]
~~Game store pages are dynamic as you can increase them and i doubt they made any locks. Meaning that it is far easier to just seek value and directly take it from save than create some sort of check on how much store pages save file should have. Obviously this is not something we can check in game files but there is a way for small test it. Increasing space might be verbotten but how about increasing number just a little so it stays withing confines of original space ?~~

~~The other kind of check they could do for same function would be to check those books status and then take pages amount from that. But imho it is far more error prone rather than taking it directly which means they shouldn't do it like that.~~

**Comment by perkel666** [comment]
Scratch that i just noticed that each slot has its own value. Which means adding any slots means overwriting something. Shame.

Hmmm.. Then how about alternative ? Something like GD item assistant or Diablo keeper ? Save manager already has ability to spawn any item you want so it is not like you would have to rework a lot it.

Basically use last page of box in game as some sort of item transfer tool and previous one as receiver. So when you have MHXX save editor open on a save it will do check of save file every minute or so and it will pick up to its own database what you have in last page of box and remove it from it. And when player will want to get it back he would just click it that database "transfer to item box" which would put that item into receiver page of the box.

You can sort of emulate it like that already but there is no way to write what is your own stuff you made. I think also it should be new "issue". So i will write it better and open up new issue about new "feature".

Please close this issue
