### ISSUE TITLE
Beast skill on charisma cat in 3rd taught Moves slot

### ISSUE THREAD

**Issue by barff** [pagewin/MHXXSaveEditor#6]
Charisma cats have this automagically when assigning Support group type. Ex.: Selecting BBBCCC, BBCCCCC, etc. places a beast skill in the 3rd learned skill slot

**Comment by pagewin** [comment]
Is this in the editor also or only in game after cheating?

**Comment by barff** [comment]
Can't edit learned moves via editor, at least not currently. Need to go in-game then choose "Forget a Move/Skill" to view it. I simply teach a new Move and choose the 3rd slot to forcefully remove/overwrite it. This makes the cat "legal" for in-mission use.

**Comment by pagewin** [comment]
It's probably this or somewhere nearby
`EditPalicoDialog.cs:445`
```csharp
switch (Convert.ToInt32(mainForm.player.PalicoData[(selectedPalico * Constants.SIZEOF_PALICO) + 0x25]))
    {
        case 0: // Charisma
            comboBoxLearnedSupportMoves.Enabled = false;
            break;
        /* ... */
        case 7: // Beast
            comboBoxEquippedSupportMoves.Items.Add("Rousing Roar");
            break;
```
Thanks #10 

What the hell is `0x25`? Well, Ukee made a nice wiki page about the save data structure: https://github.com/mineminemine/MHXXSaveEditor/wiki/MHXX-'system'-file-structure
It's the bias. Don't know why these weren't incorporated into the list of constants already used.

**Comment by pagewin** [comment]
Misunderstood the original issue, Charisma cats are supposed to be able to learn 3 moves from other cats and the editor only accounted for 2.
